# Generated by Django 4.2.7 on 2023-11-24 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_number_alter_customuser_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="number",
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                default=1,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Noto'g'ri telefon raqami formati",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        18, message="Siz 18 yoshdan kichik bo'lgansiz"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
