# Generated by Django 4.2.7 on 2023-11-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mijoz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ism", models.CharField(max_length=255)),
                ("nomer", models.CharField(max_length=255)),
            ],
        ),
    ]
