# Generated by Django 4.2.7 on 2023-11-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_mijoz"),
    ]

    operations = []
