# Generated by Django 4.2.7 on 2023-11-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_delete_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="mijoz",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
