# Generated by Django 4.2.7 on 2023-11-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_mijoz_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="mijoz",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
